# ####################################################################

#  Created by Genus(TM) Synthesis Solution 18.10-p003_1 on Mon Jun 29 12:26:04 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000.0fF
set_units -time 1000.0ps

# Set the current design
current_design riscv

create_clock -name "clk" -period 20.0 -waveform {0.0 10.0} [get_ports clk]
set_clock_transition 0.1 [get_clocks clk]
set_load -pin_load 0.01 [get_ports {pc_out[31]}]
set_load -pin_load 0.01 [get_ports {pc_out[30]}]
set_load -pin_load 0.01 [get_ports {pc_out[29]}]
set_load -pin_load 0.01 [get_ports {pc_out[28]}]
set_load -pin_load 0.01 [get_ports {pc_out[27]}]
set_load -pin_load 0.01 [get_ports {pc_out[26]}]
set_load -pin_load 0.01 [get_ports {pc_out[25]}]
set_load -pin_load 0.01 [get_ports {pc_out[24]}]
set_load -pin_load 0.01 [get_ports {pc_out[23]}]
set_load -pin_load 0.01 [get_ports {pc_out[22]}]
set_load -pin_load 0.01 [get_ports {pc_out[21]}]
set_load -pin_load 0.01 [get_ports {pc_out[20]}]
set_load -pin_load 0.01 [get_ports {pc_out[19]}]
set_load -pin_load 0.01 [get_ports {pc_out[18]}]
set_load -pin_load 0.01 [get_ports {pc_out[17]}]
set_load -pin_load 0.01 [get_ports {pc_out[16]}]
set_load -pin_load 0.01 [get_ports {pc_out[15]}]
set_load -pin_load 0.01 [get_ports {pc_out[14]}]
set_load -pin_load 0.01 [get_ports {pc_out[13]}]
set_load -pin_load 0.01 [get_ports {pc_out[12]}]
set_load -pin_load 0.01 [get_ports {pc_out[11]}]
set_load -pin_load 0.01 [get_ports {pc_out[10]}]
set_load -pin_load 0.01 [get_ports {pc_out[9]}]
set_load -pin_load 0.01 [get_ports {pc_out[8]}]
set_load -pin_load 0.01 [get_ports {pc_out[7]}]
set_load -pin_load 0.01 [get_ports {pc_out[6]}]
set_load -pin_load 0.01 [get_ports {pc_out[5]}]
set_load -pin_load 0.01 [get_ports {pc_out[4]}]
set_load -pin_load 0.01 [get_ports {pc_out[3]}]
set_load -pin_load 0.01 [get_ports {pc_out[2]}]
set_load -pin_load 0.01 [get_ports {pc_out[1]}]
set_load -pin_load 0.01 [get_ports {pc_out[0]}]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -network_latency_included -add_delay -rise -min 0.0 [get_ports clk]
set_input_delay -clock [get_clocks clk] -clock_fall -network_latency_included -add_delay -fall -min 0.0 [get_ports clk]
set_input_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports clk]
set_input_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports rst]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[31]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[30]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[29]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[28]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[27]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[26]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[25]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[24]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[23]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[22]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[21]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[20]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[19]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[18]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[17]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[16]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[15]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[14]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[13]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[12]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 2.0 [get_ports {pc_out[0]}]
set_input_transition 0.1 [get_ports clk]
set_input_transition 0.1 [get_ports rst]
set_wire_load_mode "enclosed"
set_dont_use [get_lib_cells slow_vdd1v0/HOLDX1]
set_clock_uncertainty -setup 0.05 [get_clocks clk]
set_clock_uncertainty -hold 0.05 [get_clocks clk]
