
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Jun 29 2026 12:25:19 IST (Jun 29 2026 06:55:19 UTC)

// Verification Directory fv/riscv 

module riscv(clk, rst, pc_out);
  input clk, rst;
  output [31:0] pc_out;
  wire clk, rst;
  wire [31:0] pc_out;
  wire [31:0] pc_next;
  wire add_191_26_n_170, add_191_26_n_175, add_191_26_n_180,
       add_191_26_n_185, add_191_26_n_190, add_191_26_n_195,
       add_191_26_n_200, add_191_26_n_205;
  wire add_191_26_n_210, add_191_26_n_215, add_191_26_n_220,
       add_191_26_n_225, add_191_26_n_230, add_191_26_n_235,
       add_191_26_n_240, add_191_26_n_245;
  wire add_191_26_n_250, add_191_26_n_255, add_191_26_n_260,
       add_191_26_n_265, add_191_26_n_270, add_191_26_n_275,
       add_191_26_n_280, add_191_26_n_285;
  wire add_191_26_n_290, add_191_26_n_295, add_191_26_n_300,
       add_191_26_n_305, n_0, n_1;
  assign pc_out[0] = 1'b0;
  assign pc_out[1] = 1'b0;
  INVXL g48119(.A (rst), .Y (n_1));
  DFFRX1 \pc_reg[2] (.RN (n_1), .CK (clk), .D (n_0), .Q (pc_out[2]),
       .QN (n_0));
  XNOR2X1 add_191_26_g339__8780(.A (pc_out[31]), .B (add_191_26_n_170),
       .Y (pc_next[31]));
  OA21X1 add_191_26_g340__4296(.A0 (pc_out[30]), .A1
       (add_191_26_n_175), .B0 (add_191_26_n_170), .Y (pc_next[30]));
  NAND2X1 add_191_26_g341__3772(.A (pc_out[30]), .B (add_191_26_n_175),
       .Y (add_191_26_n_170));
  AOI2BB1XL add_191_26_g342__1474(.A0N (pc_out[29]), .A1N
       (add_191_26_n_180), .B0 (add_191_26_n_175), .Y (pc_next[29]));
  AND2XL add_191_26_g343__4547(.A (pc_out[29]), .B (add_191_26_n_180),
       .Y (add_191_26_n_175));
  AOI2BB1XL add_191_26_g344__9682(.A0N (pc_out[28]), .A1N
       (add_191_26_n_185), .B0 (add_191_26_n_180), .Y (pc_next[28]));
  AND2XL add_191_26_g345__2683(.A (pc_out[28]), .B (add_191_26_n_185),
       .Y (add_191_26_n_180));
  AOI2BB1XL add_191_26_g346__1309(.A0N (pc_out[27]), .A1N
       (add_191_26_n_190), .B0 (add_191_26_n_185), .Y (pc_next[27]));
  AND2XL add_191_26_g347__6877(.A (pc_out[27]), .B (add_191_26_n_190),
       .Y (add_191_26_n_185));
  AOI2BB1XL add_191_26_g348__2900(.A0N (pc_out[26]), .A1N
       (add_191_26_n_195), .B0 (add_191_26_n_190), .Y (pc_next[26]));
  AND2XL add_191_26_g349__2391(.A (pc_out[26]), .B (add_191_26_n_195),
       .Y (add_191_26_n_190));
  AOI2BB1XL add_191_26_g350__7675(.A0N (pc_out[25]), .A1N
       (add_191_26_n_200), .B0 (add_191_26_n_195), .Y (pc_next[25]));
  AND2XL add_191_26_g351__7118(.A (pc_out[25]), .B (add_191_26_n_200),
       .Y (add_191_26_n_195));
  AOI2BB1XL add_191_26_g352__8757(.A0N (pc_out[24]), .A1N
       (add_191_26_n_205), .B0 (add_191_26_n_200), .Y (pc_next[24]));
  AND2XL add_191_26_g353__1786(.A (pc_out[24]), .B (add_191_26_n_205),
       .Y (add_191_26_n_200));
  AOI2BB1XL add_191_26_g354__5953(.A0N (pc_out[23]), .A1N
       (add_191_26_n_210), .B0 (add_191_26_n_205), .Y (pc_next[23]));
  AND2XL add_191_26_g355__5703(.A (pc_out[23]), .B (add_191_26_n_210),
       .Y (add_191_26_n_205));
  AOI2BB1XL add_191_26_g356__7114(.A0N (pc_out[22]), .A1N
       (add_191_26_n_215), .B0 (add_191_26_n_210), .Y (pc_next[22]));
  AND2XL add_191_26_g357__5266(.A (pc_out[22]), .B (add_191_26_n_215),
       .Y (add_191_26_n_210));
  AOI2BB1XL add_191_26_g358__2250(.A0N (pc_out[21]), .A1N
       (add_191_26_n_220), .B0 (add_191_26_n_215), .Y (pc_next[21]));
  AND2XL add_191_26_g359__6083(.A (pc_out[21]), .B (add_191_26_n_220),
       .Y (add_191_26_n_215));
  AOI2BB1XL add_191_26_g360__2703(.A0N (pc_out[20]), .A1N
       (add_191_26_n_225), .B0 (add_191_26_n_220), .Y (pc_next[20]));
  AND2XL add_191_26_g361__5795(.A (pc_out[20]), .B (add_191_26_n_225),
       .Y (add_191_26_n_220));
  AOI2BB1XL add_191_26_g362__7344(.A0N (pc_out[19]), .A1N
       (add_191_26_n_230), .B0 (add_191_26_n_225), .Y (pc_next[19]));
  AND2XL add_191_26_g363__1840(.A (pc_out[19]), .B (add_191_26_n_230),
       .Y (add_191_26_n_225));
  AOI2BB1XL add_191_26_g364__5019(.A0N (pc_out[18]), .A1N
       (add_191_26_n_235), .B0 (add_191_26_n_230), .Y (pc_next[18]));
  AND2XL add_191_26_g365__1857(.A (pc_out[18]), .B (add_191_26_n_235),
       .Y (add_191_26_n_230));
  AOI2BB1XL add_191_26_g366__9906(.A0N (pc_out[17]), .A1N
       (add_191_26_n_240), .B0 (add_191_26_n_235), .Y (pc_next[17]));
  AND2XL add_191_26_g367__8780(.A (pc_out[17]), .B (add_191_26_n_240),
       .Y (add_191_26_n_235));
  AOI2BB1XL add_191_26_g368__4296(.A0N (pc_out[16]), .A1N
       (add_191_26_n_245), .B0 (add_191_26_n_240), .Y (pc_next[16]));
  AND2XL add_191_26_g369__3772(.A (pc_out[16]), .B (add_191_26_n_245),
       .Y (add_191_26_n_240));
  AOI2BB1XL add_191_26_g370__1474(.A0N (pc_out[15]), .A1N
       (add_191_26_n_250), .B0 (add_191_26_n_245), .Y (pc_next[15]));
  AND2XL add_191_26_g371__4547(.A (pc_out[15]), .B (add_191_26_n_250),
       .Y (add_191_26_n_245));
  AOI2BB1XL add_191_26_g372__9682(.A0N (pc_out[14]), .A1N
       (add_191_26_n_255), .B0 (add_191_26_n_250), .Y (pc_next[14]));
  AND2XL add_191_26_g373__2683(.A (pc_out[14]), .B (add_191_26_n_255),
       .Y (add_191_26_n_250));
  AOI2BB1XL add_191_26_g374__1309(.A0N (pc_out[13]), .A1N
       (add_191_26_n_260), .B0 (add_191_26_n_255), .Y (pc_next[13]));
  AND2XL add_191_26_g375__6877(.A (pc_out[13]), .B (add_191_26_n_260),
       .Y (add_191_26_n_255));
  AOI2BB1XL add_191_26_g376__2900(.A0N (pc_out[12]), .A1N
       (add_191_26_n_265), .B0 (add_191_26_n_260), .Y (pc_next[12]));
  AND2XL add_191_26_g377__2391(.A (pc_out[12]), .B (add_191_26_n_265),
       .Y (add_191_26_n_260));
  AOI2BB1XL add_191_26_g378__7675(.A0N (pc_out[11]), .A1N
       (add_191_26_n_270), .B0 (add_191_26_n_265), .Y (pc_next[11]));
  AND2XL add_191_26_g379__7118(.A (pc_out[11]), .B (add_191_26_n_270),
       .Y (add_191_26_n_265));
  AOI2BB1XL add_191_26_g380__8757(.A0N (pc_out[10]), .A1N
       (add_191_26_n_275), .B0 (add_191_26_n_270), .Y (pc_next[10]));
  AND2XL add_191_26_g381__1786(.A (pc_out[10]), .B (add_191_26_n_275),
       .Y (add_191_26_n_270));
  AOI2BB1XL add_191_26_g382__5953(.A0N (pc_out[9]), .A1N
       (add_191_26_n_280), .B0 (add_191_26_n_275), .Y (pc_next[9]));
  AND2XL add_191_26_g383__5703(.A (pc_out[9]), .B (add_191_26_n_280),
       .Y (add_191_26_n_275));
  AOI2BB1XL add_191_26_g384__7114(.A0N (pc_out[8]), .A1N
       (add_191_26_n_285), .B0 (add_191_26_n_280), .Y (pc_next[8]));
  AND2XL add_191_26_g385__5266(.A (pc_out[8]), .B (add_191_26_n_285),
       .Y (add_191_26_n_280));
  AOI2BB1XL add_191_26_g386__2250(.A0N (pc_out[7]), .A1N
       (add_191_26_n_290), .B0 (add_191_26_n_285), .Y (pc_next[7]));
  AND2XL add_191_26_g387__6083(.A (pc_out[7]), .B (add_191_26_n_290),
       .Y (add_191_26_n_285));
  AOI2BB1XL add_191_26_g388__2703(.A0N (pc_out[6]), .A1N
       (add_191_26_n_295), .B0 (add_191_26_n_290), .Y (pc_next[6]));
  AND2XL add_191_26_g389__5795(.A (pc_out[6]), .B (add_191_26_n_295),
       .Y (add_191_26_n_290));
  AOI2BB1XL add_191_26_g390__7344(.A0N (pc_out[5]), .A1N
       (add_191_26_n_300), .B0 (add_191_26_n_295), .Y (pc_next[5]));
  AND2XL add_191_26_g391__1840(.A (pc_out[5]), .B (add_191_26_n_300),
       .Y (add_191_26_n_295));
  AOI2BB1XL add_191_26_g392__5019(.A0N (pc_out[4]), .A1N
       (add_191_26_n_305), .B0 (add_191_26_n_300), .Y (pc_next[4]));
  AND2XL add_191_26_g393__1857(.A (pc_out[4]), .B (add_191_26_n_305),
       .Y (add_191_26_n_300));
  AOI2BB1XL add_191_26_g394__9906(.A0N (pc_out[2]), .A1N (pc_out[3]),
       .B0 (add_191_26_n_305), .Y (pc_next[3]));
  AND2XL add_191_26_g395__8780(.A (pc_out[2]), .B (pc_out[3]), .Y
       (add_191_26_n_305));
  DFFRHQX1 \pc_reg[31] (.RN (n_1), .CK (clk), .D (pc_next[31]), .Q
       (pc_out[31]));
  DFFRHQX1 \pc_reg[30] (.RN (n_1), .CK (clk), .D (pc_next[30]), .Q
       (pc_out[30]));
  DFFRHQX1 \pc_reg[29] (.RN (n_1), .CK (clk), .D (pc_next[29]), .Q
       (pc_out[29]));
  DFFRHQX1 \pc_reg[28] (.RN (n_1), .CK (clk), .D (pc_next[28]), .Q
       (pc_out[28]));
  DFFRHQX1 \pc_reg[27] (.RN (n_1), .CK (clk), .D (pc_next[27]), .Q
       (pc_out[27]));
  DFFRHQX1 \pc_reg[26] (.RN (n_1), .CK (clk), .D (pc_next[26]), .Q
       (pc_out[26]));
  DFFRHQX1 \pc_reg[25] (.RN (n_1), .CK (clk), .D (pc_next[25]), .Q
       (pc_out[25]));
  DFFRHQX1 \pc_reg[24] (.RN (n_1), .CK (clk), .D (pc_next[24]), .Q
       (pc_out[24]));
  DFFRHQX1 \pc_reg[23] (.RN (n_1), .CK (clk), .D (pc_next[23]), .Q
       (pc_out[23]));
  DFFRHQX1 \pc_reg[22] (.RN (n_1), .CK (clk), .D (pc_next[22]), .Q
       (pc_out[22]));
  DFFRHQX1 \pc_reg[21] (.RN (n_1), .CK (clk), .D (pc_next[21]), .Q
       (pc_out[21]));
  DFFRHQX1 \pc_reg[20] (.RN (n_1), .CK (clk), .D (pc_next[20]), .Q
       (pc_out[20]));
  DFFRHQX1 \pc_reg[19] (.RN (n_1), .CK (clk), .D (pc_next[19]), .Q
       (pc_out[19]));
  DFFRHQX1 \pc_reg[18] (.RN (n_1), .CK (clk), .D (pc_next[18]), .Q
       (pc_out[18]));
  DFFRHQX1 \pc_reg[17] (.RN (n_1), .CK (clk), .D (pc_next[17]), .Q
       (pc_out[17]));
  DFFRHQX1 \pc_reg[16] (.RN (n_1), .CK (clk), .D (pc_next[16]), .Q
       (pc_out[16]));
  DFFRHQX1 \pc_reg[15] (.RN (n_1), .CK (clk), .D (pc_next[15]), .Q
       (pc_out[15]));
  DFFRHQX1 \pc_reg[14] (.RN (n_1), .CK (clk), .D (pc_next[14]), .Q
       (pc_out[14]));
  DFFRHQX1 \pc_reg[13] (.RN (n_1), .CK (clk), .D (pc_next[13]), .Q
       (pc_out[13]));
  DFFRHQX1 \pc_reg[12] (.RN (n_1), .CK (clk), .D (pc_next[12]), .Q
       (pc_out[12]));
  DFFRHQX1 \pc_reg[11] (.RN (n_1), .CK (clk), .D (pc_next[11]), .Q
       (pc_out[11]));
  DFFRHQX1 \pc_reg[10] (.RN (n_1), .CK (clk), .D (pc_next[10]), .Q
       (pc_out[10]));
  DFFRHQX1 \pc_reg[9] (.RN (n_1), .CK (clk), .D (pc_next[9]), .Q
       (pc_out[9]));
  DFFRHQX1 \pc_reg[8] (.RN (n_1), .CK (clk), .D (pc_next[8]), .Q
       (pc_out[8]));
  DFFRHQX1 \pc_reg[7] (.RN (n_1), .CK (clk), .D (pc_next[7]), .Q
       (pc_out[7]));
  DFFRHQX1 \pc_reg[6] (.RN (n_1), .CK (clk), .D (pc_next[6]), .Q
       (pc_out[6]));
  DFFRHQX1 \pc_reg[5] (.RN (n_1), .CK (clk), .D (pc_next[5]), .Q
       (pc_out[5]));
  DFFRHQX1 \pc_reg[4] (.RN (n_1), .CK (clk), .D (pc_next[4]), .Q
       (pc_out[4]));
  DFFRHQX1 \pc_reg[3] (.RN (n_1), .CK (clk), .D (pc_next[3]), .Q
       (pc_out[3]));
endmodule

